import React, {useState} from 'react';
import {Alert, FlatList, Pressable, StyleSheet, Text, View} from 'react-native';
import {useDispatch, useSelector} from 'react-redux';
import EditModal from '../components/EditModal'; import {addList, deleteList, updateList} from '../store/todosSlice'; import {logout} from '../store/authSlice'; import {colors, shadows} from '../theme';
export default function ListsScreen({navigation}) {
  const dispatch = useDispatch(); const lists = useSelector(s => s.todos.lists); const email = useSelector(s => s.auth.user?.email); const [editing, setEditing] = useState(null); const [showModal, setShowModal] = useState(false);
  const remove = list => Alert.alert('Delete list?', `“${list.title}” and all its tasks will be removed.`, [{text: 'Cancel', style: 'cancel'}, {text: 'Delete', style: 'destructive', onPress: () => dispatch(deleteList(list.id))}]);
  const renderItem = ({item}) => { const done = item.items.filter(x => x.completed).length; return <Pressable onPress={() => navigation.navigate('Todos', {listId: item.id})} style={({pressed}) => [styles.card, pressed && styles.pressed]}><View style={styles.icon}><Text style={styles.iconText}>☷</Text></View><View style={styles.cardBody}><Text style={styles.cardTitle}>{item.title}</Text><Text style={styles.meta}>{done} of {item.items.length} complete</Text></View><Pressable hitSlop={10} onPress={() => {setEditing(item); setShowModal(true);}}><Text style={styles.action}>Edit</Text></Pressable><Pressable hitSlop={10} onPress={() => remove(item)}><Text style={[styles.action, styles.delete]}>Delete</Text></Pressable></Pressable>; };
  return <View style={styles.page}><View style={styles.header}><View><Text style={styles.hello}>MY LISTS</Text><Text style={styles.email} numberOfLines={1}>{email}</Text></View><Pressable onPress={() => dispatch(logout())}><Text style={styles.logout}>Sign out</Text></Pressable></View><FlatList data={lists} keyExtractor={x => x.id} renderItem={renderItem} contentContainerStyle={[styles.list, !lists.length && styles.emptyList]} ListEmptyComponent={<View style={styles.empty}><Text style={styles.emptyIcon}>✦</Text><Text style={styles.emptyTitle}>Make your first list</Text><Text style={styles.emptyText}>Group tasks by project, routine, or anything else.</Text></View>}/><Pressable accessibilityLabel="Add list" onPress={() => {setEditing(null); setShowModal(true);}} style={styles.fab}><Text style={styles.fabText}>＋</Text></Pressable><EditModal visible={showModal} title={editing ? 'Rename list' : 'New list'} label="List name" initialValue={editing?.title} onCancel={() => setShowModal(false)} onSave={value => {dispatch(editing ? updateList({id: editing.id, title: value}) : addList(value)); setShowModal(false);}}/></View>;
}
const styles = StyleSheet.create({page: {flex: 1, backgroundColor: colors.background}, header: {padding: 22, flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center'}, hello: {fontSize: 24, fontWeight: '900', color: colors.text}, email: {color: colors.muted, marginTop: 4, maxWidth: 240}, logout: {color: colors.primary, fontWeight: '700'}, list: {padding: 18, paddingBottom: 100}, emptyList: {flexGrow: 1, justifyContent: 'center'}, card: {...shadows.card, backgroundColor: colors.surface, borderRadius: 18, padding: 16, marginBottom: 12, flexDirection: 'row', alignItems: 'center', gap: 12}, pressed: {opacity: .75}, icon: {width: 42, height: 42, borderRadius: 13, backgroundColor: colors.tint, alignItems: 'center', justifyContent: 'center'}, iconText: {color: colors.primary, fontSize: 22}, cardBody: {flex: 1}, cardTitle: {fontWeight: '700', fontSize: 17, color: colors.text}, meta: {fontSize: 13, color: colors.muted, marginTop: 4}, action: {fontSize: 12, fontWeight: '700', color: colors.primary}, delete: {color: colors.danger}, empty: {alignItems: 'center', padding: 30}, emptyIcon: {fontSize: 45, color: colors.primary}, emptyTitle: {fontSize: 21, fontWeight: '800', color: colors.text, marginTop: 15}, emptyText: {color: colors.muted, textAlign: 'center', marginTop: 8}, fab: {...shadows.card, position: 'absolute', right: 24, bottom: 28, width: 60, height: 60, borderRadius: 20, backgroundColor: colors.primary, alignItems: 'center', justifyContent: 'center'}, fabText: {color: '#FFF', fontSize: 30}});
