import React, {useLayoutEffect, useState} from 'react';
import {Alert, FlatList, Pressable, StyleSheet, Text, View} from 'react-native';
import {useDispatch, useSelector} from 'react-redux';
import EditModal from '../components/EditModal'; import {addItem, deleteItem, toggleItem, updateItem} from '../store/todosSlice'; import {colors} from '../theme';
export default function TodosScreen({route, navigation}) {
  const {listId} = route.params; const dispatch = useDispatch(); const list = useSelector(s => s.todos.lists.find(x => x.id === listId)); const [editing, setEditing] = useState(null); const [showModal, setShowModal] = useState(false);
  useLayoutEffect(() => navigation.setOptions({title: list?.title || 'Tasks'}), [navigation, list?.title]);
  if (!list) return <View style={styles.empty}><Text style={styles.emptyTitle}>This list no longer exists.</Text></View>;
  const remove = item => Alert.alert('Delete task?', `Remove “${item.title}”?`, [{text: 'Cancel', style: 'cancel'}, {text: 'Delete', style: 'destructive', onPress: () => dispatch(deleteItem({listId, itemId: item.id}))}]);
  return <View style={styles.page}><FlatList data={list.items} keyExtractor={x => x.id} contentContainerStyle={[styles.list, !list.items.length && styles.emptyList]} ListEmptyComponent={<View style={styles.empty}><Text style={styles.emptyIcon}>✓</Text><Text style={styles.emptyTitle}>Nothing here yet</Text><Text style={styles.emptyText}>Add a task and get moving.</Text></View>} renderItem={({item}) => <View style={styles.item}><Pressable accessibilityRole="checkbox" accessibilityState={{checked: item.completed}} onPress={() => dispatch(toggleItem({listId, itemId: item.id}))} style={[styles.check, item.completed && styles.checked]}>{item.completed ? <Text style={styles.checkmark}>✓</Text> : null}</Pressable><Text style={[styles.itemTitle, item.completed && styles.done]}>{item.title}</Text><Pressable hitSlop={10} onPress={() => {setEditing(item); setShowModal(true);}}><Text style={styles.action}>Edit</Text></Pressable><Pressable hitSlop={10} onPress={() => remove(item)}><Text style={[styles.action, styles.delete]}>Delete</Text></Pressable></View>}/><Pressable accessibilityLabel="Add task" onPress={() => {setEditing(null); setShowModal(true);}} style={styles.fab}><Text style={styles.fabText}>＋</Text></Pressable><EditModal visible={showModal} title={editing ? 'Edit task' : 'New task'} label="Task" initialValue={editing?.title} onCancel={() => setShowModal(false)} onSave={value => {dispatch(editing ? updateItem({listId, itemId: editing.id, title: value}) : addItem(listId, value)); setShowModal(false);}}/></View>;
}
const styles = StyleSheet.create({page: {flex: 1, backgroundColor: colors.background}, list: {padding: 18, paddingBottom: 100}, emptyList: {flexGrow: 1, justifyContent: 'center'}, item: {backgroundColor: colors.surface, borderRadius: 16, padding: 15, marginBottom: 10, flexDirection: 'row', alignItems: 'center', gap: 12}, check: {width: 26, height: 26, borderRadius: 8, borderWidth: 2, borderColor: colors.border, alignItems: 'center', justifyContent: 'center'}, checked: {backgroundColor: colors.success, borderColor: colors.success}, checkmark: {color: '#FFF', fontWeight: '900'}, itemTitle: {flex: 1, color: colors.text, fontSize: 16}, done: {textDecorationLine: 'line-through', color: colors.muted}, action: {fontSize: 12, fontWeight: '700', color: colors.primary}, delete: {color: colors.danger}, empty: {alignItems: 'center'}, emptyIcon: {width: 64, height: 64, borderRadius: 20, backgroundColor: colors.tint, textAlign: 'center', paddingTop: 10, color: colors.primary, fontSize: 30}, emptyTitle: {fontSize: 20, fontWeight: '800', color: colors.text, marginTop: 16}, emptyText: {color: colors.muted, marginTop: 7}, fab: {position: 'absolute', right: 24, bottom: 28, width: 60, height: 60, borderRadius: 20, backgroundColor: colors.primary, alignItems: 'center', justifyContent: 'center', elevation: 5}, fabText: {color: '#FFF', fontSize: 30}});
